### ISSUE TITLE
Mark this repository as unmaintained

### ISSUE THREAD

**Issue by andymckay** [actions/create-release#119]
Sadly we haven't got the time to maintain this repository as an official GitHub Action. In the last year or two since we originally published this, a large number of really good community Actions have appeared on the Marketplace for doing this.

We'd like to mark this repository as unmaintained and make it clear to users what their expectations should be.

People are of course free to fork this repository and maintain those forks if they like.

To do this we'll:
* [x] Remove it from the Marketplace 
* [x] Remove from any official GitHub documentation.
* [x] Change the README.md to clearly reflect its new state.
* [x] Update the README.md to point to other community Actions.
* [x] Archive this repository, putting it read-only mode. It will continue to work for all existing Action users, but won't receive any updates.

**Comment by leycec** [comment]
> In the last year or two since we originally published this, a large number of really good community Actions have appeared on the Marketplace for doing this.

...and these vaguely unspecified comparable alternatives are what, exactly? There probably should be similar GitHub Actions somewhere, but I can't actually find any. Were you just assuming *fait accompli* that viable alternatives existed when you wrote that – or did you actually find a few and assumed we could too? Because, I can't. :sob: 

@saxbophone [notes a similar problem in the preceding issue](https://github.com/actions/create-release/issues/118#issuecomment-771215311):

> It's a shame nothing else could be found on the marketplace, I think this repo is becoming unmaintained soon

**Comment by ash0x0** [comment]
@leycec Found a couple more: [marvinpinto/action-automatic-releases](https://github.com/marvinpinto/action-automatic-releases) and [softprops/action-gh-release](https://github.com/softprops/action-gh-release). I ended up using the latter, was very quick and took care of all the cases like release in a matrix and existing releases and all the possible frills with creating and uploading.
