### ISSUE TITLE
Missing Body!

### ISSUE THREAD

**Issue by eduncan911** [actions/create-release#4]
Hello!

So, why isn't the `body` parameter exposed on the create API method? :)

Looks like we can easily add it here:

https://github.com/actions/create-release/blob/master/src/create-release.js#L25

Thanks!

**Comment by IAmHughes** [comment]
Hey @eduncan911, Thank you so much for opening an issue! 🚀 

The thought behind not adding the `body` parameter to the API was that this Action is the most basic component in creating a release. It is simply used to create a release, and provides you with the URL needed to then make additional API calls to edit that Release (i.e. you can [upload-release-assets](https://github.com/actions/upload-release-asset), or perhaps use another action that generates release notes).

Additionally, release notes usually are not a "standard template" as in, each release need's a unique set of release notes. Exposing the `body` parameter as an input would mean that you need to pass in a hard coded value to your workflow to provide as an input. This hard coded value wouldn't be very useful in most situations, as you would want the notes to change on each release. I hope that makes sense 😅 

Personally, I am planning (hoping?) that I can find some time to create something like a `Edit-Release-Notes` Action that would take in `string` as input. That string can be generated however you want (maybe another step in your workflow aggregates the PR title of every PR that merged since your last release, for example).

I'm going to leave the issue open for a few days to gather additional input, then will close it out by 10/18 as a `wont fix` due to the above mentioned reasons. If I can find another way to implement this that we discuss, I'll keep it open and see what I can do 🎉

**Comment by eduncan911** [comment]
I thought it was deliberately left out.  :)

> The thought behind not adding the body parameter to the API was that this Action is the most basic component in creating a release. It is simply used to create a release, and provides you with the URL needed to then make additional API calls to edit that Release (i.e. you can upload-release-assets, or perhaps use another action that generates release notes).

This I can understand.  However, a simple Optional parameter would go a long way for basic text input (and yes, a parser of sort from another action could be used).  

Being optional shouldn't be a reason to deny.  :)

> Additionally, release notes usually are not a "standard template" as in, each release need's a unique set of release notes. Exposing the body parameter as an input would mean that you need to pass in a hard coded value to your workflow to provide as an input. This hard coded value wouldn't be very useful in most situations, as you would want the notes to change on each release. I hope that makes sense sweat_smile

Whatever the motive of the consumer/user, this is an opinionated decision.  IMO (heh, another opinion), GitHub Actions are never opinionated.  I haven't seen one to date.  Node action is highly configurable over opinions.  Even Golang, which is a highly opinionated language - is just purely configurable with no opinionated feature removed or automatically set.

By personal use, absolutely I've used this on 100s of projects.  Mostly for commit / PR logs as you mentioned, at a minimal; full-blown regression upgrades and new requirements, at the most.  

See, github releases are also RSS feeds.  Which a lot of teams use to aggregate to customers, clients, and internal teams and dashboards, release notes, etc.

Not having the ability to use the body is a blocker.

Then again, one could just copy the action down and use it locally within the repo.  :)

**Comment by csexton** [comment]
Thanks @IAmHughes for the rationale, and I am a fan of keeping things simple. However, would like to throw in my 2¢. I'd second the ability to pass in the body. 

My use case is to have this action create a draft release with to body along the lines of:

```
body: |
  Bug Fixes:

  - TODO: Describe any bug fixes

  Enhancements:

  - TODO: Describe any new features or enhancements
```

This serves as a reminder to fill in the TODOs as part of the release process. Super handy.

Unlike the assets (which require additional requests), adding a body via a new step feels cumbersome. Perhaps pass the release to another step, fetch the resource, then post an update when the API supports this attribute as part of the original create request. 

More than happy to submit a PR if you'd be open to it 😁

**Comment by csexton** [comment]
> Additionally, release notes usually are not a "standard template" as in, each release need's a unique set of release notes. Exposing the body parameter as an input would mean that you need to pass in a hard coded value to your workflow to provide as an input. This hard coded value wouldn't be very useful in most situations, as you would want the notes to change on each release.

Might make sense to do this the other way around. Have a step that creates the release notes, and passes them to an `output`. Then you could compose your action something like this:

```
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Compile Release Notes
        uses: csexton/fictional-release-note-compiler@dne
        id: notes
      - name: Create Release
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.notes.outputs.body }}
```

In this case the `Compile Release Notes` sets an output `body` that can be passed in when creating the release.

**Comment by eduncan911** [comment]
@csexton bingo. When I had the time, I was going to write a new action to compile release notes.  Yep.

**Comment by botnerd** [comment]
This would be a great addition. I have the same use case as @csexton. I've been searching for an action for creating a github draft release with a template body, but I can't find one that accepts a body as an input and returns the release URL.

**Comment by wildone** [comment]
Would be great to have this role support all of the parameters that API specifies, so that we don't have to have extra steps and write more actions that do the same thing.

official API docs for Create Repo are here https://developer.github.com/v3/repos/releases/ and body is a parameter.
{
  "tag_name": "v1.0.0",
  "target_commitish": "master",
  "name": "v1.0.0",
  "body": "Description of the release",
  "draft": false,
  "prerelease": false
}

**Comment by jmalloc** [comment]
Perhaps my usage is different to most others, or I am missing something, but I would benefit from the ability to use the tag commit message as the release body.   I do this manually at the moment simply to get the GitHub UI to render the markdown from the tag commit message. By convention I use the latest release notes as the tag commit message.

**Comment by csexton** [comment]
@jmalloc that a good idea, I’d just been using  lightweight tags until now. But an annotation makes a ton of sense. 

Does the GitHub UI populate the body with that message by default?

**Comment by jmalloc** [comment]
No, it doesn't populate the body textarea.  It will render the tag commit message before a release is created (though not as markdown, see below). I usually copy this and paste it into the text area when creating the release proper.

<img width="812" alt="Screen Shot 2019-10-21 at 10 26 03 am" src="https://user-images.githubusercontent.com/761536/67169202-5e83b780-f3ed-11e9-84cf-fd5bc507f34c.png">

**Comment by IAmHughes** [comment]
> This I can understand. However, a simple Optional parameter would go a long way for basic text input (and yes, a parser of sort from another action could be used).
> More than happy to submit a PR if you'd be open to it 😁

@eduncan911 and @csexton this isn't a bad idea at all, PRs are very much welcome! Shouldn't be TOO bad of a change, and another test or two should cover the additional path. 🎉 

> official API docs for Create Repo are here https://developer.github.com/v3/repos/releases/ and body is a parameter

@wildone 💯 agree. I stated the original though on leaving it out earlier in this thread, but I agree it can be exposed as an optional parameter.

Since this action is in JavaScript, we are using Ocktokit/rest.js, and the documentation surrounding the `create-release` endpoint can be found [here](https://octokit.github.io/rest.js/#octokit-routes-repos-create-release) for anyone wanting to submit PRs ❤️

**Comment by csexton** [comment]
@IAmHughes Cool, I will take a crack at it. And keep things a straight forward as possible, I understand why you don't want to get fancy/clever.

**Comment by 1138-4EB** [comment]
Considering the different comments in this issue, I'd suggest `body:` to accept either the path to a file or a (multiline) string. Cases such as https://github.com/actions/create-release/issues/4#issuecomment-543467269 or https://github.com/actions/create-release/issues/4#issuecomment-543469402 would be identified as strings and pushed raw. At the same time, `CHANGELOG.md` or `RELEASE_NOTES.txt` or `${{ github.workspace }}/release_notes.md` would be read before adding them to the body. The case in https://github.com/actions/create-release/issues/4#issuecomment-544308897 can be solved by writing the commit message to a file, or getting it from the context.

To make it explicit, `body: "file: <path_to_file>"` can be used. For example:

```js
const body = core.getInput('body', {required: true});

...

body: ((body.slice(0,5) == 'file:') ? createReadStream(body) : body),
```

**Comment by jnovack** [comment]
I imagined something like the main feature of [nytimes/Chronicler](https://github.com/nytimes/Chronicler) being added since the project is now defunct (much like newspapers in general, I suppose `¯\_(ツ)_/¯`)

**Comment by Tyrrrz** [comment]
I imagine it would be convenient if we could set all properties of a release using `create-release`. It doesn't seem like a good UX to have to look for another action that edits description, etc.

Currently, I'm missing this as I usually put the changelog in the description of the release in CD, but now I have to do it manually.
