### ISSUE TITLE
Unable to do scenario: draft release, upload asset, publish a release

### ISSUE THREAD

**Issue by EskiMag** [actions/create-release#6]
I am not able to create this workflow:
1. Draft a release
2. Upload release assets
3. Publish a release

The reason I want to do it this way, is to have the link to assets already included in the notification email about the new release.
Is there a way to do this without using the `hub` or GitHub API manually?

**Comment by IAmHughes** [comment]
@EskiMag that's a great point on the workflow suggestion, and I can see it's usefulness. This Action is a primitive, in that it only creates a basic release (or draft if you pass that parameter in), but doesn't allow you to edit releases. I have plans to eventually write an `edit-release` primitive Action that would allow likely allow you to do something like publishing a draft release, but for now I'd have to point you to the [GitHub Marketplace](https://github.com/marketplace) to locate something, otherwise I'd always encourage you to develop your own Actions as well 🚀.

Closing as this would be out of scope of this Action, but noting for myself as another request to edit releases in another Action ❤️

**Comment by EskiMag** [comment]
@IAmHughes thanks for the explanation. I was for some reason under the impression that actions under github.com/actions are maintained by GitHub. I am sorry if it's your personal activity. :)

**Comment by IAmHughes** [comment]
@EskiMag they are officially maintained by GitHub, but this one (and the `upload-release-asset` happened to be side projects I was doing, versus something that I can dedicate more time to right now.

That said, I may still be doing contributions on my own time 😋 

I hope one day to have an `edit-release` action created like I was saying, but that would be outside of the scope of this primitive action. 👍

**Comment by Flamefire** [comment]
I was just about to open a new issue about the exact same thing. Take this as another request to provide such an action in the "semi-officcial" actions :)
