### ISSUE TITLE
How can we change the owner of the release creator?

### ISSUE THREAD

**Issue by shivapoudel** [actions/create-release#67]
https://github.com/actions/create-release/blob/master/src/create-release.js#L26

**Comment by chancancode** [comment]
The line you selected is actually talking about the owner part of the fully qualified repository name ("**actions**/create-release"). If you are asking about the username that is associated with the release (@github-actions by default), I believe that is based on who made the API call, i.e. what token you used. You can, for example, create a personal access token and pass that instead of `secrets.GITHUB_TOKEN`, and the release will be published by your personal user.

**Comment by shivapoudel** [comment]
@chancancode You mean I can add secret like this so it is not public in the workflow file right:
![image](https://user-images.githubusercontent.com/3774827/81150127-21ed6700-8f9f-11ea-860d-2abb21b40d5e.png)

**Comment by chancancode** [comment]
Yes but I am not sure if you can call it `GITHUB_TOKEN`. IIRC, `GITHUB_*` is reserved? Anyway, no harm in trying, if it doesn't work you will probably find out right away in that UI. If I am right, you can just call it anything else and adjust your workflow file accordingly.

**Comment by shivapoudel** [comment]
Okay, it works great. Thanks!
